[build]
    publish = "out"
    command = "yarn build"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Robots-Tag = "noindex, nofollow"